#Project Setup
general:
  projectName: "openui5-sample-app"

  
steps:
  mtaBuild:
    mtaBuildTool: cloudMbt
    applicationName: "testapp"
    
  karmaExecuteTests:
    runCommand: "npm test"
    stashContent: []
